import pytz

# Timezone
IST = pytz.timezone('Asia/Kolkata')

# Tokens
NIFTY_TOKEN = "99926000"

# 💰 THE MASTER FUND CONFIGURATION
PAPER_CAPITAL = 100000  
ALLOCATION_PER_TRADE = 0.10  
MAX_CONCURRENT_TRADES = int(1 / ALLOCATION_PER_TRADE) 

# 🛡️ POSITIONAL RISK PARAMS
POSITIONAL_TARGET_PCT = 0.03 
INITIAL_SL_PCT = 0.015       
TRAILING_SL_PCT = 0.01